# Generated by Django 4.1.1 on 2022-10-03 17:27

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='org_price',
            field=models.FloatField(default=234.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sell_price',
            field=models.FloatField(default=234.0),
            preserve_default=False,
        ),
    ]
