# Generated by Django 4.1.1 on 2022-10-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_org_price_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small_decs',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
