# Generated by Django 4.1.1 on 2022-10-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_profile_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'cancelled'), ('Pending', 'pending'), ('Out for delivery', 'out for delivery'), ('Delivered', 'delivered'), ('Shipped', 'shipped')], default='Pending', max_length=150),
        ),
    ]
