# Generated by Django 4.1.1 on 2022-10-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'out for delivery'), ('Cancelled', 'cancelled'), ('Pending', 'pending'), ('Delivered', 'delivered'), ('Shipped', 'shipped')], default='Pending', max_length=150),
        ),
    ]
